- README.md
Why?
===
The sections didn't exist?
What Changed?
===
Contributors and Insperation Sections added to the README.md
> Contributors and Insperation README Additons

- README.md
Why?
===
Forgot to save the contributors and inspiration sections.
What Changed?
===
Saved, adding the two sections.
> Missed Contributors and Inspiration Sections

- README.md
Why?
===
Formatting wasn't showing they way I thought it would.
What Changed?
===
Added to spaces and return at the end of each line and manually added the links.
> Fix Contributor Formatting

- README.md
Why?
===
Messed up Renee's username.
What Changed?
===
Corrected Renee's username.
> Renee Username Typo Fix

- .gitignore
- README.md
- package.json
- tsconfig.json
- typings.json
Why?
===
Roster outdated and needed the Angular 2 dependencies.
Need to ignore generated files so they aren't commited.
What Changed?
===
Updated the README.md roster
Added package.json tsconfig.json and typings.json for Angular 2
and updated .gitignore to ignore new folders. Added ignore for
generated javascript and typescript.
> Added Angular 2 Dependencies And Updated Roster

- .gitignore
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- config/application.rb
- public/app/main.js.map
- public/app/main.ts
- public/app/visual-tales-app.component.html
- public/app/visual-tales-app.component.ts
Why?
===
Angular 2 wasn't running.
What Changed?
===
Maded changes so Angular 2 would run.
> Angular 2 Startup

- Gemfile
- Gemfile.lock
- README.md
- app/models/character.rb
- app/models/pose.rb
- app/models/scene.rb
- app/uploaders/background_uploader.rb
- app/uploaders/portrait_uploader.rb
- app/uploaders/pose_uploader.rb
Image now get resized upon uploading.
> Added carrierwave to upload and resize images

- .gitignore
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
- gulpfile.js
- package.json
- public/app/home/home.component.html
- public/app/home/home.component.scss
- public/app/home/home.component.ts
- public/app/home/home.ts
- public/app/scenes/scene-editor.component.ts
- public/app/scenes/scenes.ts
- public/app/stories/stories.component.ts
- public/app/stories/stories.ts
- public/app/stories/story-editor.component.ts
- public/app/stories/story.service.ts
- public/app/stories/view-story.component.ts
- public/app/visual-tales-app.component.html
- public/app/visual-tales-app.component.ts
Why?
===
There were no base components or layout. Also the angular 2 app
was not working correctly.
What Changed?
===
Added new files that were put there to get the app up and running.
Also added the header and footer for the layout.
> Added the Base Components and Started on Layout

- gulpfile.js
Why?
===
Forgot to save a needed  Bootstrap Material Design dependency.
What Changed?
===
Added the needed  Bootstrap Material Design.
> Missed The Bootstrap Material Design

- package.json
Why?
===
Uploaded the wrong file.
What Changed?
===
Uploaded the right file.
> Package Json Bootstrap Material Design

- gulpfile.js
Why?
===
Accidently added bootstrap material.
What Changed?
===
Removed bootstrap material.
> Remove Angular Bootstrap Material

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css
- app/assets/stylesheets/custom-material-bootstrap.scss
- app/assets/stylesheets/custom-material-variables.scss
- app/assets/stylesheets/layout.scss
- public/app/home/home.component.html
- public/app/home/home.component.scss
Why?
===
Who wants an ugly webiste?
What Changed?
===
Finished the header and changed the color
> Finished Basic Layout

- app/assets/javascripts/application.js
- public/app/home/home.component.ts
- public/app/main.ts
- public/app/stories/stories.component.html
- public/app/stories/stories.component.ts
- public/app/stories/stories.ts
- public/app/stories/story.service.ts
- public/app/visual-tales-app.component.ts
Why?
===
Needed to add the story service but getting errors
from adding service.
What Changed?
===
Added the Story Service and called it in the stories component
> Added Story Service With Errors

- public/app/data/tag.service.ts
> Added Tag Service

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/api/characters_controller.rb
- app/controllers/api/events_controller.rb
- app/controllers/api/poses_controller.rb
- app/controllers/api/stories_controller.rb
- app/controllers/api/tags_controller.rb
- app/controllers/api_controller.rb
- app/models/character.rb
- app/models/pose.rb
- app/models/story_tag.rb
- app/models/tag.rb
- config/routes.rb
- db/seeds.rb
- spec/controllers/api/characters_controller_spec.rb
- spec/controllers/api/poses_controller_spec.rb
- spec/controllers/api/stories_controller_spec.rb
- spec/controllers/api/tags_controller_spec.rb
New api documentation...  see link in readme.md
> updated the api

- public/app/stories/stories.component.html
- public/app/stories/stories.component.ts
What Changed?
===
Added observables to the input and now get results back when typing.
> Started Story Search

- app/assets/stylesheets/layout.scss
- public/app/components/image-panel-list.component.html
- public/app/components/image-panel-list.component.scss
- public/app/components/image-panel-list.component.ts
- public/app/stories/stories.component.html
- public/app/stories/stories.component.ts
What Changed?
===
Added image panel list coomponent
Updated layout to remove border
Updated stories component
> Finished Text Searching Feature and Styling

- public/app/components/image-panel-list.component.html
- public/app/data/data.ts
- public/app/data/tag.service.ts
- public/app/data/visual-tales-http.service.ts
- public/app/main.ts
- public/app/stories/story.service.ts
What Changed?
===
Added a Visual Tales Http Service and made it so all the services
used that.
Also made it so you can click on stories.
> Added Visual Tales Http Service

- public/app/home/home.component.ts
- public/app/stories/story-editor.component.html
- public/app/stories/story-editor.component.ts
What Changed?
===
Polo added Story Editor Stuff and I fixed the merge conflicts.
> Making stories be editable on UI

- app/assets/stylesheets/layout.scss
- public/app/components/image-panel-list.component.html
- public/app/data/story.service.ts
- public/app/data/visual-tales-http.service.ts
- public/app/home/home.component.html
- public/app/home/home.component.scss
- public/app/home/home.component.ts
- public/app/stories/story-editor.component.html
- public/app/stories/story-editor.component.ts
What Changed?
===
I added characters and scenes to the story editor.
Made it so the scenes route to the scene editor.
> Updated the Story Editor

- README.md
> I'm Tom Dunlap

- README.md
... in markdown at least.
Without it the names get smashed together.
> Sometimes trailing whitespace is a good thing.
